# -*- coding: utf-8 -*-
"""Multimodal_RAG_NovaCore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLZLbxh7pXgKUbDT7-NHO5xTvxva0CTB
"""

from google.colab import userdata

os.environ["GROQ_API_KEY"] = userdata.get("GROQ_API_KEY")
os.environ["PINECONE_API_KEY"] = userdata.get("PINECONE_API_KEY")

# Commented out IPython magic to ensure Python compatibility.
# %pip install -qU \
    langchain \
    langchain-core \
    langchain-groq \
    langchain-huggingface \
    langchain-pinecone \
    pinecone \
    sentence-transformers \
    pymupdf \
    groq \
    pandas \
    tabulate \
    pillow

# Commented out IPython magic to ensure Python compatibility.
# %pip uninstall -y pillow
# %pip install --no-cache-dir --force-reinstall pillow

import os
import io
import time
import base64
from pathlib import Path

import fitz  # PyMuPDF
import pandas as pd

from PIL import Image
from IPython.display import display

from groq import Groq
from pinecone import Pinecone, ServerlessSpec

from langchain_core.documents import Document
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import StrOutputParser
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_groq import ChatGroq
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.messages import HumanMessage
from langchain_pinecone import PineconeVectorStore


# =========================================================================
# CONFIG
# =========================================================================

PDF_PATH = "/content/NovaCore_Multimodal_Company_Report_2026.pdf"

TEXT_MODEL = "openai/gpt-oss-20b"
VISION_MODEL = "qwen/qwen3.8-27b"
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"

PINECONE_INDEX_NAME = "novacore-multimodal-rag"
PINECONE_NAMESPACE = "fy2026-demo"

IMAGE_DIR = Path("novacore_extracted_images")
IMAGE_DIR.mkdir(exist_ok=True)

CHUNK_SIZE = 1000
CHUNK_OVERLAP = 150

# --- API keys: read from environment only. Never hardcode real keys in code. ---
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
PINECONE_API_KEY = os.getenv("PINECONE_API_KEY")

if not GROQ_API_KEY:
    raise EnvironmentError(
        "GROQ_API_KEY is not set. Set it as an environment variable "
        "(e.g. in Colab: os.environ['GROQ_API_KEY'] = userdata.get('GROQ_API_KEY'))."
    )
if not PINECONE_API_KEY:
    raise EnvironmentError(
        "PINECONE_API_KEY is not set. Set it as an environment variable "
        "before running this script."
    )

print("PDF:", PDF_PATH)
print("Pinecone index:", PINECONE_INDEX_NAME)
print("Pinecone namespace:", PINECONE_NAMESPACE)

# --- Clients / models ---
groq_client = Groq(api_key=GROQ_API_KEY)

vision_llm = ChatGroq(model_name=VISION_MODEL, temperature=0.7)
text_llm = ChatGroq(model_name=TEXT_MODEL, temperature=0.0)

print("API clients are ready.")


# =========================================================================
# STAGE 3 (helpers used during extraction): DESCRIBE VISUALS
# =========================================================================

def image_to_data_uri(image_path):
    """Encode an image file as a base64 JPEG data URI (resized, for vision LLM input)."""
    image_path = Path(image_path)

    with Image.open(image_path) as img:
        img = img.convert("RGB")
        img.thumbnail((1600, 1600))

        buffer = io.BytesIO()
        img.save(buffer, format="JPEG", quality=85)

    encoded = base64.b64encode(buffer.getvalue()).decode("utf-8")
    return f"data:image/jpeg;base64,{encoded}"


def summarize_visual(image_path, page_number):
    """Ask the vision model to describe a chart/diagram/image extracted from the PDF."""
    image_data = image_to_data_uri(image_path)

    prompt = f"""
This visual was extracted from page {page_number} of the NovaCore FY2026 company report.

Describe the useful business information visible in the visual.

If it is a chart or graph:
- mention important values
- mention highest/lowest values
- mention the main trend

If it is a diagram:
- identify important components
- explain the flow or relationships

If it is a normal business image:
- describe the useful factual information

Keep the description concise and factual.
"""
    message = HumanMessage(
        content=[
            {"type": "text", "text": prompt},
            {"type": "image_url", "image_url": {"url": image_data}},
        ]
    )
    response = vision_llm.invoke([message])
    return response.content.strip()


# =========================================================================
# STAGE 1 + STAGE 2: LOAD & EXTRACT (text / tables / images per page)
# =========================================================================

def extract_text(page):
    """Pull raw text from one PDF page."""
    text = page.get_text("text").strip()
    return text if text else None


def create_text_document(text, page_number, source):
    return Document(
        page_content=text,
        metadata={"page": page_number, "modality": "text", "source": source},
    )


def extract_tables(page):
    """Pull tables from one PDF page and convert each to a markdown Document."""
    table_documents = []

    try:
        tables = page.find_tables().tables

        for table_number, table in enumerate(tables, start=1):
            df = table.to_pandas()
            if df.empty:
                continue

            table_text = df.to_markdown(index=False)
            document = Document(
                page_content=table_text,
                metadata={
                    "page": page.number + 1,
                    "modality": "table",
                    "table_number": table_number,
                },
            )
            table_documents.append(document)

    except Exception as error:
        print("Table extraction error:", error)

    return table_documents


def extract_images(page, pdf, image_dir, processed_images):
    """Pull images from one PDF page, save them, and describe them via the vision model."""
    image_documents = []
    page_number = page.number + 1
    images = page.get_images(full=True)

    for image_number, image_info in enumerate(images, start=1):
        xref = image_info[0]

        if xref in processed_images:  # skip duplicates
            continue
        processed_images.add(xref)

        image_data = pdf.extract_image(xref)
        image_bytes = image_data["image"]
        extension = image_data["ext"]

        image_path = image_dir / f"page_{page_number}_image_{image_number}.{extension}"
        image_path.write_bytes(image_bytes)

        try:
            summary = summarize_visual(image_path=image_path, page_number=page_number)

            document = Document(
                page_content=summary,
                metadata={
                    "page": page_number,
                    "modality": "visual",
                    "image_path": str(image_path),
                    "image_number": image_number,
                },
            )
            image_documents.append(document)

        except Exception as error:
            print(f"Vision error on page {page_number}:", error)

    return image_documents


def process_page(page, pdf, image_dir, processed_images, source):
    """Extract text + tables + images (with descriptions) from a single page."""
    documents = []
    page_number = page.number + 1
    print(f"Processing page {page_number}...")

    text = extract_text(page)
    if text:
        documents.append(create_text_document(text=text, page_number=page_number, source=source))

    table_documents = extract_tables(page)
    for document in table_documents:
        document.metadata["source"] = source
    documents.extend(table_documents)

    image_documents = extract_images(
        page=page, pdf=pdf, image_dir=image_dir, processed_images=processed_images
    )
    for document in image_documents:
        document.metadata["source"] = source
    documents.extend(image_documents)

    return documents


def load_and_extract_multimodal_documents(pdf_path, image_dir):
    """
    STAGE 1 (LOAD) + STAGE 2 (EXTRACT): open the PDF and walk every page,
    extracting text, tables, and vision-described images into Documents.
    """
    pdf_path = Path(pdf_path)
    image_dir = Path(image_dir)
    image_dir.mkdir(parents=True, exist_ok=True)

    pdf = fitz.open(str(pdf_path))
    all_documents = []
    processed_images = set()

    for page in pdf:
        page_documents = process_page(
            page=page,
            pdf=pdf,
            image_dir=image_dir,
            processed_images=processed_images,
            source=pdf_path.name,
        )
        all_documents.extend(page_documents)

    pdf.close()
    return all_documents


# =========================================================================
# STAGE 4: CHUNK
# =========================================================================

def chunk_documents(documents, chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP):
    """
    Split long TEXT documents into RAG-sized chunks. Tables and vision summaries
    are already compact/atomic units of meaning, so we pass them through unchanged
    and only chunk the raw page-text documents.
    """
    splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
    )

    chunked_documents = []

    for doc in documents:
        if doc.metadata.get("modality") == "text":
            splits = splitter.split_documents([doc])
            chunked_documents.extend(splits)
        else:
            chunked_documents.append(doc)

    return chunked_documents


# =========================================================================
# STAGE 5: EMBED
# =========================================================================

def build_embedding_model(model_name=EMBEDDING_MODEL):
    embeddings = HuggingFaceEmbeddings(
        model_name=model_name,
        encode_kwargs={"normalize_embeddings": True},
    )
    embedding_dimension = len(embeddings.embed_query("dimension check"))
    print("Embedding model:", model_name)
    print("Embedding dimension:", embedding_dimension)
    return embeddings, embedding_dimension


# =========================================================================
# STAGE 6: INDEX (VECTOR STORE)
# =========================================================================

def get_or_create_pinecone_index(index_name, dimension, api_key):
    pc = Pinecone(api_key=api_key)

    if not pc.has_index(index_name):
        print("Creating Pinecone index...")
        pc.create_index(
            name=index_name,
            dimension=dimension,
            metric="cosine",
            spec=ServerlessSpec(cloud="aws", region="us-east-1"),
        )
        while not pc.describe_index(index_name).status["ready"]:
            print("Waiting for Pinecone index...")
            time.sleep(2)
        print("Pinecone index created.")
    else:
        print("Pinecone index already exists.")

    return pc.Index(index_name)


def build_vectorstore(chunked_documents, embeddings, index_name, namespace, api_key):
    """Clear the namespace, then embed + upsert all chunked documents."""
    index = get_or_create_pinecone_index(
        index_name=index_name,
        dimension=len(embeddings.embed_query("dimension check")),
        api_key=api_key,
    )
    print("Connected to:", index_name)

    try:
        index.delete(delete_all=True, namespace=namespace)
        print("Cleared namespace:", namespace)
    except Exception as error:
        print("Namespace was probably empty. Continuing...", error)

    vectorstore = PineconeVectorStore(
        index_name=index_name,
        embedding=embeddings,
        namespace=namespace,
    )
    vectorstore.add_documents(chunked_documents)
    print("Documents uploaded to Pinecone.")

    return vectorstore


# =========================================================================
# STAGE 7: RETRIEVE
# =========================================================================

def build_retriever(vectorstore, k=5):
    retriever = vectorstore.as_retriever(search_kwargs={"k": k})
    print("Retriever is ready.")
    return retriever


# =========================================================================
# STAGE 8: GENERATE (RAG chains: text-only + vision-augmented)
# =========================================================================

rag_prompt = ChatPromptTemplate.from_template(
    """
You are a helpful assistant answering questions about the
NovaCore Systems FY2026 company report.

Use ONLY the retrieved context below.

If the answer is not available in the context, say:
"I could not find that information in the report."

Mention page numbers when possible.

CONTEXT:
{context}

QUESTION:
{question}

ANSWER:
"""
)

text_rag_chain = rag_prompt | text_llm | StrOutputParser()


def format_context(retrieved_docs):
    parts = []
    for doc in retrieved_docs:
        page = doc.metadata.get("page")
        modality = doc.metadata.get("modality")
        parts.append(f"[Page {page} | {modality.upper()}]\n{doc.page_content}")
    return "\n\n".join(parts)


def answer_with_vision(question, context, image_paths):
    image_paths = image_paths[:3]

    content = [
        {
            "type": "text",
            "text": f"""
You are answering questions about the NovaCore Systems FY2026 report.

Use ONLY the retrieved context and the attached retrieved visuals.

RETRIEVED CONTEXT:
{context}

QUESTION:
{question}

Instructions:
- Answer factually.
- Use the attached visuals when relevant.
- Mention page numbers.
- If the information is missing, say you could not find it.
""",
        }
    ]

    for image_path in image_paths:
        content.append(
            {"type": "image_url", "image_url": {"url": image_to_data_uri(image_path)}}
        )

    response = groq_client.chat.completions.create(
        model=VISION_MODEL,
        messages=[{"role": "user", "content": content}],
        temperature=0,
        max_completion_tokens=900,
    )

    return response.choices[0].message.content.strip()


# =========================================================================
# STAGE 9: QUERY INTERFACE (end-to-end)
# =========================================================================

def ask_rag(question, retriever, show_sources=True, show_images=False):
    # Retrieve
    retrieved_docs = retriever.invoke(question)

    # Build context
    context = format_context(retrieved_docs)

    # Collect any visuals returned by retrieval
    image_paths = []
    for doc in retrieved_docs:
        if doc.metadata.get("modality") == "visual":
            image_path = doc.metadata.get("image_path")
            if image_path and Path(image_path).exists():
                image_paths.append(image_path)

    # Generate (route to vision-augmented chain if visuals were retrieved)
    if image_paths:
        answer = answer_with_vision(question=question, context=context, image_paths=image_paths)
    else:
        answer = text_rag_chain.invoke({"context": context, "question": question})

    print("\nQUESTION:")
    print(question)
    print("\nANSWER:")
    print(answer)

    if show_sources:
        print("\nPINECONE RETRIEVED SOURCES:")
        for i, doc in enumerate(retrieved_docs, start=1):
            print(f"{i}. Page {doc.metadata.get('page')} | {doc.metadata.get('modality')}")

    if show_images and image_paths:
        print("\nRETRIEVED VISUALS:")
        for image_path in image_paths:
            display(Image.open(image_path))

    return {"answer": answer, "documents": retrieved_docs, "image_paths": image_paths}


# =========================================================================
# STAGE 10: RUN THE PIPELINE END TO END
# =========================================================================

if __name__ == "__main__":
    # ---- STAGE 1 + 2: load & extract ----
    documents = load_and_extract_multimodal_documents(
        pdf_path=PDF_PATH,
        image_dir=IMAGE_DIR,
    )
    print("\nTotal documents extracted:", len(documents))

    rows = [
        {
            "page": doc.metadata["page"],
            "modality": doc.metadata["modality"],
            "preview": doc.page_content[:140].replace("\n", " "),
        }
        for doc in documents
    ]
    summary_df = pd.DataFrame(rows)
    display(summary_df)
    print("Documents by modality:")
    display(summary_df["modality"].value_counts())

    # ---- STAGE 4: chunk ----
    chunked_documents = chunk_documents(documents)
    print("Total chunks after splitting:", len(chunked_documents))

    # ---- STAGE 5: embed ----
    embeddings, embedding_dimension = build_embedding_model()

    # ---- STAGE 6: index / vector store ----
    vectorstore = build_vectorstore(
        chunked_documents=chunked_documents,
        embeddings=embeddings,
        index_name=PINECONE_INDEX_NAME,
        namespace=PINECONE_NAMESPACE,
        api_key=PINECONE_API_KEY,
    )

    # ---- STAGE 7: retriever ----
    retriever = build_retriever(vectorstore, k=5)

    # ---- STAGE 8 + 9: generation / query ----
    ask_rag(
        "What does NovaCore Systems do and where is the company headquartered?",
        retriever=retriever,
    )

    ask_rag(
        "According to the revenue graph, which quarter had the highest revenue?",
        retriever=retriever,
        show_images=True,
    )

    ask_rag(
        "According to the supply-chain diagram, what is the critical quality-control point?",
        retriever=retriever,
        show_images=True,
    )

    ask_rag(
        "How did average support resolution time change from January to August?",
        retriever=retriever,
        show_images=True,
    )

    ask_rag(
        """
Give me a short FY2026 performance summary.
Include:
1. total revenue,
2. fastest-growing region,
3. support-resolution improvement,
4. solar share at the Penang facility.
""",
        retriever=retriever,
    )

pip install -U langchain-text-splitters

